---
title: "JHU_RM project"
author: "mbh038"
date: "Monday, June 15, 2015"
output: pdf_document
---

"Is an automatic or manual transmission better for MPG"
"Quantify the MPG difference between automatic and manual transmissions"

```{r load data}
library(dplyr)
data(mtcars)
str(mtcars)
#make an am factor column
amf<-factor(mtcars$am)
mtwide<-mutate(mtcars,amf)
```
```{r gpm plot}
library(ggplot2)
mtwide$gpm<-100/mtwide$mpg
g<-ggplot(data=mtwide,aes(x=wt,y=gpm,colour=amf))+
        geom_point()+
        geom_smooth(method=lm)+
        #facet_wrap(~amf,shrink=FALSE)+
        labs(x = "Weight / 1000 lb",y = "Gallons per 100 miles")
g
```
```{r regression of mpg on just am}
lm1<-lm(gpm~factor(amf),data=mtwide)
lm1
```
So if all the other variates were randomly assigneed to the 2 transmission groups we coulc conclude that automatic cars had a higher mpg than manual cars. This is physically plausible.



##Play
```{r q4 LIB 8 exercises}
data(mtcars)
t.test(mtcars$mpg)
```
```{r q5 LIB 8 exercises}
qt(0.975,8)*1/3
```
```{r q7 LIB 8 exercises}
library(dplyr)
mt4<-filter(mtcars,cyl==4)
mt6<-filter(mtcars,cyl==6)
t.test(mt4$mpg,mt6$mpg,pairs=FALSE,var.equal=TRUE)
#The interval is above zero, suggesting 4 is better than 6 in the terms of MPG.
```